#!/usr/bin/env python3

import os
import sys

args = sys.argv[1:]

dict = {
    "SYSTEM": "uname -srvmpio",
    "awk": "awk --version | head -1",
    "cc": "cc --version | head -1",
    "grep": "grep --version | head -1",
    "groff": "groff --version | head -1",
    "latex": "latex --version | grep 'Compiled with\\|3.14\\|version'",
    "tex": "tex --version | head -2"
}

for p in args:
    if p in dict:
        os.system(dict[p])
    else:
        print("\"", p, "\" not in program list.", sep="")
        break
    

